version: 1

models:
  - name: stg_orders
    description: This table contains information about customer orders.

    columns:
      - name: order_key
        description: Primary key of the orders table.
        tests:
          - unique
          - not_null

      - name: order_cust_key
        description: Foreign key to the customers table.


      - name: order_status
        description: Status of the order.

      - name: order_total_price
        description: Total price of the order.


      - name: order_date
        description: Date the order was placed.


      - name: order_priority
        description: Priority of the order.


      - name: order_clerk
        description: Clerk who processed the order.


      - name: order_ship_priority
        description: Priority of the shipment.


      - name: order_comment
        description: Comment about the order.
 
  - name: stg_customer
    description: This table contains information about customers.

    columns:
      - name: cust_key
        description: Customer key
        tests:
          - unique
          - not_null

      - name: cust_name
        description: Customer name

      - name: cust_address
        description: Customer address

      - name: cust_nation_key
        description: Customer nation key

      - name: cust_phone
        description: Customer phone number

      - name: cust_account_balance
        description: Customer account balance

      - name: cust_market_segment
        description: Customer market segment

      - name: cust_comment
        description: Customer comment

  - name: stg_lineitem
    columns:
      - name: lineitem_key
        description: Surrogate key for the lineitem table
        tests:
          - unique
          - not_null

      - name: lineitem_order_key
        description: Order key for the lineitem

      - name: lineitem_part_key
        description: Part key for the lineitem

      - name: lineitem_supplied_key
        description: Supplier key for the lineitem

      - name: lineitem_linenumber
        description: Line number for the lineitem

      - name: lineitem_quantity
        description: Quantity for the lineitem

      - name: lineitem_extended_price
        description: Extended price for the lineitem

      - name: lineitem_discount
        description: Discount for the lineitem

      - name: lineitem_tax
        description: Tax for the lineitem

      - name: lineitem_line_total
        description: Line total for the lineitem

      - name: lineitem_line_total_tax
        description: Line total tax for the lineitem

      - name: lineitem_return_flag
        description: Return flag for the lineitem

      - name: lineitem_line_status
        description: Line status for the lineitem

      - name: lineitem_ship_date
        description: Ship date for the lineitem

      - name: lineitem_commit_date
        description: Commit date for the lineitem

      - name: lineitem_receipt_date
        description: Receipt date for the lineitem

      - name: lineitem_ship_instruct
        description: Ship instructions for the lineitem

      - name: lineitem_ship_mode
        description: Ship mode for the lineitem

      - name: lineitem_comment
        description: Comment for the lineitem

  - name: stg_nation
    columns:
      - name: nation_key
        description: Primary key of the table.
        tests:
          - unique
          - not_null

      - name: nation_name
        description: Name of the nation.

      - name: nation_region_key
        description: Foreign key to the regions table.

      - name: nation_comment
        description: Comment for the nation.

    tables:
    - name: parts
      columns:
        - name: part_key
          description: Primary key of the table.
          tests:
            - unique
            - not_null

        - name: part_name
          description: Name of the part.

        - name: part_mrgr
          description: Manufacturer of the part.

        - name: part_brand
          description: Brand of the part.

        - name: part_type
          description: Type of the part.

        - name: part_size
          description: Size of the part.

        - name: part_container
          description: Container that the part is stored in.

        - name: part_retail_price
          description: Retail price of the part.

        - name: part_comment
          description: xomment for the part.